Get rid of NPE when there is an error parsing the header.
Summary:
Fixes the NPE from returning null instead of a valid MapOutputStatus

2012-08-30 20:24:43,252 WARN org.apache.hadoop.mapred.ReduceTask: MapOutputCopier attempt_201208291906.128836_0001_r_000085_0.8 Invalid map id
java.lang.IllegalArgumentException: TaskAttemptId string :  is not properly formed
	at org.apache.hadoop.mapreduce.TaskAttemptID.forName(TaskAttemptID.java:170)
	at org.apache.hadoop.mapred.TaskAttemptID.forName(TaskAttemptID.java:108)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.getMapOutput(ReduceTask.java:1719)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.copyOutput(ReduceTask.java:1589)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.copyHostOutput(ReduceTask.java:1542)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.run(ReduceTask.java:1474)
2012-08-30 20:24:43,253 INFO org.apache.hadoop.mapred.ReduceTask: MapOutputCopier attempt_201208291906.128836_0001_r_000085_0.8 finishing 1
2012-08-30 20:24:43,253 INFO org.apache.hadoop.mapred.ReduceTask: Task attempt_201208291906.128836_0001_r_000085_0: Failed fetch #1 from attempt_201208291906.128836_0001_m_003792_0
2012-08-30 20:24:43,253 FATAL org.apache.hadoop.mapred.Task: attempt_201208291906.128836_0001_r_000085_0 : Map output copy failure : java.lang.NullPointerException
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.copyOutput(ReduceTask.java:1591)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.copyHostOutput(ReduceTask.java:1542)
	at org.apache.hadoop.mapred.ReduceTask$ReduceCopier$MapOutputCopier.run(ReduceTask.java:1474)

Test Plan: compiled

Reviewers: dms, kevinwilfong, rvadali

Reviewed By: rvadali