[Raid Corona BugFix] Catch throwable in JobClient and RaidNode and include corona libs in the raidnode classpath
Summary:
After I push the corona release, raidnode fails to submit raid jobs but no error is
shown in the log. After investigating, I realize the problem happens at getClass
and a throwable is thrown (java.lang.NoClassDefFoundError: org/apache/thrift/TFieldIdEnum)
which is not caught by either JobClient and RaidNode

Include the Corona lib in the bin/hadoop and make JobClient and RaidNode catches throwable

Test Plan: deploy

Reviewers: dms, aching, pyang, rvadali

Reviewed By: rvadali